### PR TITLE
Add esp32-eth-clk-out17 variant

### PR DESCRIPTION
**Pull request by kasperl**

### CODE REVIEW

**Comment by kasperl** [comment]
```
$ diff toolchains/esp32/sdkconfig.defaults toolchains/esp32-eth-rmii/sdkconfig.defaults 
41a42,45
> # CONFIG_ETH_RMII_CLK_INPUT is not set
> CONFIG_ETH_RMII_CLK_OUTPUT=y
> # CONFIG_ETH_RMII_CLK_OUTPUT_GPIO0 is not set
> CONFIG_ETH_RMII_CLK_OUT_GPIO=17
```

**Review by floitsch — APPROVED** [review]
LGTM.

**Comment by floitsch** [comment]
maybe the name should be rmii-output

**Comment by kasperl** [comment]
PTAL.

**Pull request merged**
