### PR TITLE
Disable SPIRAM on S3 for now due to #1785

### PR DESCRIPTION
**Pull request by erikcorry**

### CODE REVIEW

**Comment by erikcorry** [comment]
See issue #1785

**Review by kasperl — APPROVED** [review]
What does this mean for the spiram-octo variant? Does the patch apply?

**Comment by floitsch** [comment]
> What does this mean for the spiram-octo variant? Does the patch apply?

Just tested it, and, unfortunately, no. Does not apply.
This change requires an update to the `envelopes` repository.

**Comment by floitsch** [comment]
That said: is the octo variant even meaningful if there is no spiram?

**Comment by kasperl** [comment]
> That said: is the octo variant even meaningful if there is no spiram?

No, it isn't so maybe we should just drop it until we can bring it back later?

**Pull request merged**
