### PR TITLE
feat(dns): Query AAAA records from DNS resolver

### PR DESCRIPTION
**Pull request by BraunPhilipp**
This an initial PR to support IPv6 on the Toit platform. @floitsch @erikcorry

### CODE REVIEW

**Review by erikcorry — COMMENTED** [review]
Please change the name from `--accept_aaaa` to `--accept_ipv6`

**Comment by erikcorry** [comment]
@cla-bot check

**Comment by kasperl** [comment]
@cla-bot check

**Comment by erikcorry** [comment]
The IP address you get in the test seems to vary, depending on where in the world the test is run.  Therefore the tests fails as written.

**Review by erikcorry — APPROVED** [review]

**Pull request merged**
