### PR TITLE
Add ESP32 provisioning lib and example.

### PR DESCRIPTION
**Pull request by donghengqaz**

### CODE REVIEW

**Comment by donghengqaz** [comment]
Please ignore the BLE primitive driver modification, when feature of setting BLE ADV response field is done, I will remove this part.

**Comment by kasperl** [comment]
Hi @donghengqaz! Thank you for your patience. I'll get this reviewed tomorrow :)

**Comment by donghengqaz** [comment]
> Hi @donghengqaz! Thank you for your patience. I'll get this reviewed tomorrow :)

Thank you @kasperl , from the 21st, I will take 7 days off from office, so the code may not be updated in these 7 days, but I will see your suggestions.

**Comment by kasperl** [comment]
Should this be a separate package? It is pure Toit code and it is completely optional.

It is much faster to iterate on as a separate package and you can tweak it to your needs. We have a good deal of packages out there and we can help set it up with a GitHub action so it automatically pushes to pkg.toit.io.

**Comment by donghengqaz** [comment]
> Should this be a separate package? It is pure Toit code and it is completely optional.
> 
> It is much faster to iterate on as a separate package and you can tweak it to your needs. We have a good deal of packages out there and we can help set it up with a GitHub action so it automatically pushes to pkg.toit.io.

OK, making this as a package sound better.

**Comment by floitsch** [comment]
@donghengqaz If you want to I can set up a repository with template files.
If we put it under our umbrella (github.com/toitlang or github.com/toitware) we can then take over ownership and maintenance.

**Comment by donghengqaz** [comment]
> @donghengqaz If you want to I can set up a repository with template files. If we put it under our umbrella (github.com/toitlang or github.com/toitware) we can then take over ownership and maintenance.

@floitsch Yes, please help to set up it.

**Comment by donghengqaz** [comment]
> > @donghengqaz If you want to I can set up a repository with template files. If we put it under our umbrella (github.com/toitlang or github.com/toitware) we can then take over ownership and maintenance.
> 
> @floitsch Yes, please help to set up it.

@kasperl @floitsch besides this, I plan to add more toit application based on esp-idf's application, suck as esp-now IOT network it looks like that adding these application to a separated repo instead of toit, managing these as packages is better.

**Comment by floitsch** [comment]
> > @donghengqaz If you want to I can set up a repository with template files. If we put it under our umbrella (github.com/toitlang or github.com/toitware) we can then take over ownership and maintenance.
> 
> @floitsch Yes, please help to set up it.

Here you go: https://github.com/toitware/toit-provision

**Comment by donghengqaz** [comment]
@floitsch @kasperl Code is added to https://github.com/toitware/toit-provision/pull/3, but BLE Response setting should be support in toit.

**Pull request closed without merging**
