### PR TITLE
Fix load-global-var bytecode.

### PR DESCRIPTION
**Pull request by floitsch**
The wide variant wasn't immediately following the non-wide one.

### CODE REVIEW

**Review by kasperl — APPROVED** [review]
Looks good to me.

**Review by kasperl — APPROVED** [review]
Looks good to me.

But you will need to fix the bytecode table here: https://github.com/toitlang/toit/blob/master/tools/snapshot.toit#L785.

**Comment by floitsch** [comment]
Done, and added a test.

**Review by kasperl — COMMENTED** [review]
Still looks good!

**Pull request merged**
