### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by snxx-lppxx**

### CODE REVIEW

**Comment by kasperl** [comment]
Thank you, @snxx-lppxx! I will take a look at the changes soon. In the mean time, you can take a look at our guidelines for contributing [here](https://github.com/toitlang/toit/blob/master/CONTRIBUTING.md).

**Comment by kasperl** [comment]
Hi again @snxx-lppxx. Did you take a look at the contribution guidelines?

**Comment by snxx-lppxx** [comment]
Hello @kasperl! Yeah, I looked, but I don't understand how to register for CLA.

**Comment by kasperl** [comment]
Send an email to open-source@toit.io indicating your request to sign the CLA and we will respond with a document ready for your electronic signature. Please include a link to your GitHub user profile page in the request to make it easier to identify your contributions going forward.

:)

**Comment by kasperl** [comment]
Rechecking CLA status: @cla-bot check.

**Pull request merged**
