### PR TITLE
feat(esp32s3): Add ESP32-S3 platform

### PR DESCRIPTION
**Pull request by donghengqaz**

### CODE REVIEW

**Comment by donghengqaz** [comment]
There are 3 issues to be fixed:

1. compiling C3 will cause a error, and I create PR for this:
https://github.com/toitware/esp-idf/pull/72
2. compiling with cmake based on esp-idf may cause more IRAM cost, then linking failed, for this I currently have to close this option: CONFIG_SPIRAM_CACHE_WORKAROUND, and try to find out the key
3. maybe pass ESP32_CHIP to program `tools/firmware.toit` and select target space based on this is better ?

**Comment by kasperl** [comment]
Please recheck, @cla-bot.

**Comment by kasperl** [comment]
@clabot Recheck.

**Comment by kasperl** [comment]
@cla-bot check

**Comment by donghengqaz** [comment]
It's glad to see the S3 related PR is [merged](https://github.com/toitlang/toit/pull/1065), so close this PR.

**Pull request closed without merging**
