### PR TITLE
I2s read to buffer

### PR DESCRIPTION
**Pull request by erikcorry**
New PR, same content as #591 by @mikkeldamsgaard

### CODE REVIEW

**Comment by erikcorry** [comment]
LGTM

**Comment by erikcorry** [comment]
This currently is missing something.  @mikkeldamsgaard  if you push updates to your own  branch I'll pull them into this CL for the test bots.

30/90 Test #299: health-lib/serial/protocols/i2s.toit ....................................***Failed    0.24 sec
<sdk>/i2s.toit:124:17: error: Unresolved identifier: 'i2s_read_to_buffer_'
        read := i2s_read_to_buffer_ i2s_ buffer
                ^~~~~~~~~~~~~~~~~~~

CMake Error at tests/tools/health_run.cmake:80 (message):
  Unexpected error

**Comment by mikkeldamsgaard** [comment]
Updated the original branch with the missing primitive configuration. How do I run tests before pushing?

**Comment by erikcorry** [comment]
You can't run the tests, I have to push to the branch in our repo.

I messed that up, but I think I fixed it with --force.

**Review by kasperl — APPROVED** [review]
Looks good to me.

**Pull request merged**
